CREATE TABLE `members` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`usrname` VARCHAR(65) NOT NULL,
	`passwd` VARCHAR(40) NOT NULL,
	`keystr` CHAR(32) NULL DEFAULT NULL,
	`pwddb` VARCHAR(40) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `usrname` (`usrname`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;